config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :muscle_packages, only: [:index, :create] do
    get '/', to: 'muscle_packages#index'
    post '/record', to: 'records#index'
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/muscle_menu.rb
# == Schema Information
#
# Table name: muscle_menus
#
#  id         :bigint           not null, primary key
#  image      :string(255)      not null
#  name       :string(255)      not null
#  part       :string(255)      not null
#  spell      :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MuscleMenu < ApplicationRecord
  has_many :muscle_packages_muscle_menus, dependent: :restrict_with_error
end

app/models/muscle_package.rb
# == Schema Information
#
# Table name: muscle_packages
#
#  id         :bigint           not null, primary key
#  level      :integer          not null
#  limit_time :integer          not null
#  parts      :integer          default("all"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MusclePackage < ApplicationRecord
  enum parts: { all: 0, chest: 1, shoulder: 2, back: 3, leg: 4, arm: 5 }, _prefix: true
end

app/models/muscle_package_muscle_menu.rb
# == Schema Information
#
# Table name: muscle_package_muscle_menus
#
#  id                :bigint           not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  muscle_menu_id    :bigint           not null
#  muscle_package_id :bigint           not null
#
# Indexes
#
#  index_muscle_package_muscle_menus_on_muscle_menu_id     (muscle_menu_id)
#  index_muscle_package_muscle_menus_on_muscle_package_id  (muscle_package_id)
#
# Foreign Keys
#
#  fk_rails_...  (muscle_menu_id => muscle_menus.id)
#  fk_rails_...  (muscle_package_id => muscle_packages.id)
#
class MusclePackageMuscleMenu < ApplicationRecord
  belongs_to :muscle_menu
  belongs_to :muscle_package
end

app/models/typing_record.rb
# == Schema Information
#
# Table name: typing_records
#
#  id                :bigint           not null, primary key
#  accurancy         :integer
#  score             :integer
#  time              :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  muscle_package_id :bigint           not null
#
# Indexes
#
#  index_typing_records_on_muscle_package_id  (muscle_package_id)
#
# Foreign Keys
#
#  fk_rails_...  (muscle_package_id => muscle_packages.id)
#
class TypingRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @parts = MusclePackage.all
  end
end

app/controllers/muscle_packages_controller.rb
class MusclePackagesController < ApplicationController
  def index
    @muscle_package = params[:muscle_package]
  end


  private

  def parts_params
    params.require(:muscle_package).permit(:parts)
  end
  helper_method :parts_params
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/muscle_packages_helper.rb
module MusclePackagesHelper
end

app/views/home/index.html.erb
<div class="min-h-screen hero" style="background-image: url(<%= asset_url('brandon.jpg') %>);">
  <div class="hero-overlay bg-opacity-60">
  <div class="w-full text-center hero-content max-w-none">
    <div class="w-full ">
      <div class="flex items-center justify-center w-screen h-screen gap-3">
        <%= link_to 'Play', muscle_packages_path(muscle_package_id: 0), class: 'font-sans text-4xl whitespace-normal btn btn-primary' %>
        <%= link_to '部位別でPlay', muscle_packages_path, class: 'font-sans text-4xl whitespace-normal btn btn-primary' %>
        <%= form_tag muscle_packages_path, method: :get do %>
          <%= select_tag :parts, options_for_select(MusclePackage.parts.map { |k, v| [k.capitalize, v] }) %>
          <%= submit_tag "Submit" %>
        <% end %>
        </form>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuscleTyping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/muscle_packages/index.html.erb
<h1>MusclePackages#index</h1>
<p>Find me in app/views/muscle_packages/index.html.erb</p>

app/views/shared/_header.html.erb
<div class="shadow navbar bg-base-100">
  <div class="flex-1">
    <%= link_to 'Muscle Typing', root_path %>
  </div>
  <div class="flex-none">
    <div class="flex-shrink-0">
      <%= link_to '遊び方', class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
</div>